[project]
name = "vic3-state-merger"
version = "0.1.0"
description = "Victoria 3 States Merging Automation Script & Tutorial"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.1.0",
    "pyradox-txt-parser>=5.0.1",
    "pyyaml>=6.0.3",
]
